name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  GITHUB_PAT_NUGET: ${{ secrets.GITHUB_PAT_NUGET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: nuget add source
      run: dotnet nuget add source --username DanielBock73 --password '${{ secrets.GITHUB_TOKEN }}' --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DanielBock73/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build -p:Configuration=Release \
                     --no-restore
    - name: Package the project
      run:  dotnet pack --configuration Release 
    - name: Install gpr
      run: dotnet tool install gpr --global      
    - name: Deployment the package         
      run: gpr push ./**/*.nupkg -r 'DanielBock73/NetIdent'
